language: python # Set the build language to Python

python: 3.6.7 # Set the version of Python to use

branches: master # Set the branch to build from

install:
    - pip install sphinx sphinx_rtd_theme # Install the required dependencies

script:
    - pip install .
    - python -m sphinx -b html ./docs/source ./docs/build # Build a local version of the docs
    - touch ./docs/build/.nojekyll

deploy: # Deploy documentation to Github in the gh_pages branch
    provider: pages
    skip-cleanup: true
    keep-history: true
    github_token: $GITHUB_TOKEN
    local_dir: ./docs/build
    on:
branch: master
